version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "terraform"
  directory: "/terraform"
  schedule:
    interval: "daily"

- package-ecosystem: "npm"
  directory: "/old-packages"
  schedule:
    interval: "daily"
  versioning-strategy: increase-if-necessary
