name: 'Auto code generation experiment (2): Generate code'

on:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  generate_code:
    name: Generate code and push them
    runs-on: ubuntu-latest
    env:
      TARGET_VERSION: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Update version file
        run: |
          echo $VERSION > version.txt

      - name: Create a commit
        run: |
          git branch
          git config user.name "Auto code generator"
          git add version.txt
          git commit -m "Generate code for ${TARGET_VERSION}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
