name: Create draft release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  preprocess:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      TARGET_VERSION: ${{ github.event.pull_request.title }}
      SKIP: ${{ env.SKIP == 'true' }}
    steps:
      - name: Check labels
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, env.PULL_REQUEST_LABEL) }}
        run: |
          echo '::warning::This pull request event does not have valid label'
          echo 'SKIP=true' >> $GITHUB_ENV

      - name: Check merged status
        if: ${{ env.SKIP != 'true' && ! github.event.pull_request.merged }}
        run: |
          echo '::warning::This pull request has been just closed without merge'
          echo 'SKIP=true' >> $GITHUB_ENV

  create_draft_release:
    name: Create draft release
    needs:
      - preprocess
    if: ${{ ! needs.preprocess.outputs.SKIP }}
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: Release v${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete_working_branch:
    name: Delete working branch
    needs:
      - preprocess
    if: ${{ ! needs.preprocess.outputs.SKIP }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete working branch
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerAndRepoName = context.payload.repository.full_name.split('/');
            const owner = ownerAndRepoName[0];
            const repo = ownerAndRepoName[1];
            const ref = `heads/${context.payload.pull_request.head.ref}`;
            const res = await github.git.deleteRef({
              owner,
              repo,
              ref,
            });
            console.log(res);
