# GitHub CLIを用いて、GitHub上にプルリクエストを作成する
# 対象のリポジトリは`dzeyelid/github-learning-playground`とする
# トリガは`workflow_dispatch`で、下記の引数を得る
# - `title`: プルリクエストのタイトル
# - `body`: プルリクエストの本文

name: Create PR by CLI

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'プルリクエストのタイトル'
        required: true
      body:
        description: 'プルリクエストの本文'
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create PR by CLI
        run: |
          gh pr create \
            --title "${{ github.event.inputs.title }}" \
            --body "${{ github.event.inputs.body }}" \
        env:
          GH_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
