name: Create release draft

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo $CONTEXT | jq
        env:
          CONTEXT: ${{ toJson(github) }}
