name: 'DevOps workshop: schedule cron trigger'

on:
  schedule:
    - cron: '2 */4 21,22 2 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo Hello, world! by schedule trigger
