# This is a basic workflow to help you get started with Actions

name: 'DevOps workshop: schedule cron trigger'

# Controls when the workflow will run
on:
  schedule:
    - cron: '2 0 28 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world! by schedule trigger
