name: 'DevOps workshop: schedule cron trigger'

on:
  schedule:
    - cron: '2 */4 27,28 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo Hello, world! by schedule trigger
