name: Generate code

on:
  pull_request:
    types:
      - labeled
      - edited

env:
  PULL_REQUEST_LABEL: auto-generate

jobs:
  preprocess:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      TARGET_VERSION: ${{ github.event.pull_request.title }}
    steps:
      - name: Check labels
        if: ${{ github.event.name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, env.PULL_REQUEST_LABEL) }}
        run: |
          echo '::warning::This pull request event does not have valid label'
          exit 1

  generate_code:
    name: Generate code and push them
    needs:
      - preprocess
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Update version file
        run: |
          echo $VERSION > version.txt
        env:
          VERSION: ${{ needs.preprocess.outputs.TARGET_VERSION }}

      - name: Create a commit
        run: |
          git branch
          git config user.name "Auto code generator"
          git add version.txt
          git commit -m "Generate code for ${{ needs.preprocess.outputs.TARGET_VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
