name: Generate code

on:
  pull_request:
    types:
      - labeled
      - edited

env:
  PULL_REQUEST_LABEL: auto-generate

jobs:
  preprocess:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      TARGET_VERSION: ${{ github.event.pull_request.title }}
    steps:
      - name: Show GitHub context
        if: ${{ secret.ACTIONS_STEP_DEBUG }}
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: Check labels
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, env.PULL_REQUEST_LABEL) }}
        # run: |
        #   echo '::warning::This pull request event does not have valid label'
        #   exit 1
        run: |
          echo '::warning::This pull request event does not have valid label'
          echo "::set-output name=SKIP::true"

  generate_code:
    name: Generate code and push them
    # needs:
    #   - preprocess
    if: ${{ ! needs.preprocess.outputs.SKIP }}
    runs-on: ubuntu-latest
    steps:
      - name: Show OUTPUTS content
        if: ${{ secret.ACTIONS_STEP_DEBUG }}
        run: |
          echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJSON(needs.preprocess.outputs) }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Update version file
        run: |
          echo $VERSION > version.txt
        env:
          VERSION: ${{ needs.preprocess.outputs.TARGET_VERSION }}

      - name: Create a commit
        run: |
          git branch
          git config user.name "Auto code generator"
          git add version.txt
          git commit -m "Generate code for ${{ needs.preprocess.outputs.TARGET_VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
