name: pull request trigger test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - closed

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
