name: needs job chain demo

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $NEEDS_CONTEXT | jq
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo $NEEDS_CONTEXT | jq
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo $NEEDS_CONTEXT | jq
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
