name: needs job chain demo

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: jq $JOB_CONTEXT
        env:
          JOB_CONTEXT: ${{ fromJson(job) }}

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: jq $JOB_CONTEXT
        env:
          JOB_CONTEXT: ${{ fromJson(job) }}

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: jq $JOB_CONTEXT
        env:
          JOB_CONTEXT: ${{ fromJson(job) }}
