name: Release trigger

on:
  release:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo $CONTEXT | jq
        env:
          CONTEXT: ${{ toJson(github) }}
