name: Receive repository dispatch event

on:
  repository_dispatch:
    types:
      - create-pull-request

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context
        run: |
          echo $GITHUB_CONTEXT | jq
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      # If no release yet, this step fails as "HttpError: Not Found"
      - name: Get latest release
        id: get-latest-release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerAndRepoName = context.payload.repository.full_name.split('/');
            const owner = ownerAndRepoName[0];
            const repo = ownerAndRepoName[1];
            return github.repos.getLatestRelease({
              owner,
              repo,
            });

      - name: Show latest release
        run: |
          echo $RESULT | jq
        env:
          RESULT: ${{ fromJson(steps.get-latest-release.outputs.result) }}

      - name: Create new release
        if: ${{ steps.get-latest-release.outputs.result }}
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get-latest-release.outputs.result.tag_name }}
          version-fragment: 'feature'