name: 'Experiment: run-name'
run-name: 'This is run-name syntax: inputs.message = ${{ inputs.message }}'

on:
  workflow_dispatch:
    inputs:
      message:
        description: Leave a message
        required: true

jobs:
  show-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input message
        run: echo "The message is \"${{ inputs.message }}\""
