name: Starter workflow to build and push Docker image

on:
  workflow_dispatch:

jobs:
  build_and_push:
    uses: ./.github/workflows/reusable-docker-build-and-push.yml
    with:
      image_name: ${{ github.repository }}/simple
      context_path: containers/simple
      push: true
      registry_server_url: ${{ vars.CONTAINER_REGISTRY_SERVER }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
