name: pull request trigger test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
#       - edited
      - synchronize
      - reopened
      - closed

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.action != 'closed'
        run: |
          echo 'Hello'
          echo $GITHUB_CONTEXT | jq
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - run: echo "CLOSED"
        if: github.event.action == 'closed'
