name: Test octokit/request-action

on:
  workflow_dispatch:

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
    - name: "octokit/request-action@v2.x with :"
      uses: octokit/request-action@v2.x
      id: get_latest_release_colon
      with:
        route: GET /repos/:owner/:repo/releases/latest
        owner: octokit
        repo: request-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo latest release: ${{ toJson(steps.get_latest_release_colon.outputs.data) }}"

    - name: "octokit/request-action@v2.x with {}"
      uses: octokit/request-action@v2.x
      id: get_latest_release_curly_brace
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: octokit
        repo: request-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo latest release: ${{ toJson(steps.get_latest_release_curly_brace.outputs.data) }}"

    - name: "octokit/request-action@v2.x with conbined argument and :"
      uses: octokit/request-action@v2.x
      id: get_latest_release_combine_colon
      with:
        route: GET /repos/:repo/releases/latest
        repo: octokit/request-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo latest release: ${{ toJson(steps.get_latest_release_combine_colon.outputs.data) }}"

    - name: "octokit/request-action@v2.x with conbined argument and {}"
      uses: octokit/request-action@v2.x
      id: get_latest_release_combine_curly_brace
      with:
        route: GET /repos/{repo}/releases/latest
        repo: octokit/request-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo latest release: ${{ toJson(steps.get_latest_release_combine_curly_brace.outputs.data) }}"
