name: Azure Web App Deploy

on:
  push:
    branches:
      - main
      - webapp-deploy
    paths:
      - src/webapp
  workflow_dispatch:

env:
  DOTNET_VERSION: '3.1.x'
  AZURE_WEBAPP_NAME: 'app-playground20210216'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      WORKING_DIR: src/webapp
      AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/outputs
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      working-directory: ${{ env.WORKING_DIR }}

    # Login
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
