name: 'Webapp deployment experiment: Deploy'

on:
  workflow_call:
    inputs:
      webapp_archived_app_name:
        description: The archived app name for Web app
        required: true
        type: string
      is_production:
        description: For production or not
        default: false
        type: boolean
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_RESOURCE_GROUP_NAME:
        required: true
      AZURE_WEBAPP_NAME:
        required: true

jobs:
  pre_process:
    name: Check environment
    runs-on: windows-latest
    env:
      IS_PRODUCTION: ${{ inputs.is_production == 'true' }}
    outputs:
      is_production: ${{ env.IS_PRODUCTION }}
      staging_environment: ${{ steps.select_staging_enviroment.outputs.result }}
    steps:
      - name: Select staging environment
        id: select_staging_enviroment
        uses: actions/github-script@v6.0.0
        with:
          result-encoding: string
          script: |
            const { IS_PRODUCTION } = process.env
            const result = IS_PRODUCTION ? 'webapp_pre_production' : 'webapp_staging'
            return result

  deploy_to_staging:
    name: Deploy to staging
    needs:
      - pre_process
    env:
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_SLOT_NAME: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}
    environment:
      name: ${{ needs.pre_process.outputs.staging_environment }}
      url: ${{ steps.deploy_to_staging.outputs.webapp-url }}
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.webapp_archived_app_name }}

      # Login
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web apps staging slot
      - name: 'Deploy to staging'
        id: deploy_to_staging
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .  # Indicate the directory includes downloaded artifacts
          slot-name: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}

  deploy_to_production:
    name: Deploy to Azure Web app
    needs:
      - pre_process
      - deploy_to_staging
    environment:
      name: 'webapp_production'
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/
    runs-on: windows-latest
    if: ${{ needs.pre_process.outputs.is_production }}
    steps:
      # Login
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Swap slot to production when the updates are merged to the main branch
      - name: 'Swap slot from staging'
        run: az webapp deployment slot swap --slot "${{ secrets.AZURE_WEBAPP_SLOT_NAME }}" --name "${{ secrets.AZURE_WEBAPP_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
