name: 'Webapp deployment experiment: Deploy'

on:
  workflow_call:
    inputs:
      webapp_archived_app_name:
        description: The archived app name for Web app
        required: true
        type: string
      is_production:
        description: For production or not
        default: false
        type: boolean
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_RESOURCE_GROUP_NAME:
        required: true
      AZURE_WEBAPP_NAME:
        required: true

jobs:
  select_environment:
    name: Select environment
    runs-on: windows-latest
    outputs:
      environment: ${{ steps.select_enviroment.outputs.result }}
    steps:
      - name: Select environment
        id: select_enviroment
        uses: actions/github-script@v6.0.0
        with:
          result-encoding: string
          script: |
            console.log(process.env)
            const { IS_PRODUCTION } = process.env
            const result = is_production ? 'webapp_production' : 'webapp_staging'
            console.log(result)
            return result
          env:
            IS_PRODUCTION: ${{ inputs.is_production }}

  deploy-to-staging:
    name: Deploy to staging
    needs:
      - select_environment
    env:
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_SLOT_NAME: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}
    environment:
      name: ${{ needs.select_environment.outputs.environment }}
      url: https://${{ env.AZURE_WEBAPP_NAME }}-${{ env.AZURE_WEBAPP_SLOT_NAME }}.azurewebsites.net/
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.webapp_archived_app_name }}

      # Login
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web apps staging slot
      - name: 'Deploy to staging'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .  # Indicate the directory includes downloaded artifacts
          slot-name: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}

  deploy-to-production:
    name: Deploy to Azure Web app
    needs:
      - select_environment
      - deploy-to-staging
    env:
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
    environment:
      name: ${{ needs.select_environment.outputs.environment }}
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/
    runs-on: windows-latest
    if: ${{ inputs.is_production }}
    steps:
      # Login
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Swap slot to production when the updates are merged to the main branch
      - name: 'Swap slot from staging'
        run: az webapp deployment slot swap --slot ${{ secrets.AZURE_WEBAPP_SLOT_NAME }} --name "${{ secrets.AZURE_WEBAPP_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
