name: 'Webapp deployment experiment: Build and deploy'

on:
  push:
    branches:
    - main
    paths:
    - src/webapp/**
  pull_request:
    paths:
    - src/webapp/**
    types:
    - opened
    - synchronize
    - reopened
  workflow_dispatch:
    inputs:
      environment:
        description: Select environment
        type: environment

jobs:
  build:
    uses: ./.github/workflows/webapp-build.yml
    with:
      dotnet_version: '6.0.x'

  test:
    uses: ./.github/workflows/webapp-test.yml
    with:
      dotnet_version: '6.0.x'

  deploy-to-staging:
    needs:
      - build
    if: ${{ github.event_name != 'push' || !contains(github.event.inputs.environment, 'production') }}
    uses: ./.github/workflows/webapp-deploy.yml
    with:
      webapp_archived_app_name: ${{ needs.build.outputs.webapp_archived_app_name }}
      environment: ${{ github.event.inputs.environment || 'webapp_staging'  }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}

  deploy-to-production:
    needs:
      - build
      - test
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || contains(github.event.inputs.environment, 'production') }}
    uses: ./.github/workflows/webapp-deploy.yml
    with:
      webapp_archived_app_name: ${{ needs.build.outputs.webapp_archived_app_name }}
      environment: ${{ github.event.inputs.environment || 'webapp_production' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
